#!/bin/bash

# Adres URL do REST API Patroni na lokalnym hoście
PATRONI_API_URL="http://localhost:8008/master"

# Wykonaj zapytanie do API i sprawdź kod odpowiedzi HTTP
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${PATRONI_API_URL})

# Jeśli kod odpowiedzi to 200, węzeł jest masterem - zakończ z kodem 0 (sukces)
if [ "${HTTP_CODE}" -eq 200 ]; then
  exit 0
else
  # W przeciwnym razie, węzeł nie jest masterem - zakończ z kodem 1 (błąd)
  exit 1
fi
